#![allow(clippy::allow_attributes, reason = "clippy is weird with macros")]
#![allow(clippy::empty_structs_with_brackets, reason = "generated by macro")]

pub mod input;
mod shader_processor;

pub mod change;

mod util_types;
use input::{SourceRoot, SourceRootId};
use line_index::LineIndex;
pub use util_types::*;
use vfs::{AnchoredPath, VfsPath};

use rustc_hash::{FxHashMap, FxHashSet};
use syntax::{Parse, ParseEntryPoint};
use triomphe::Arc;
pub use vfs::FileId;

pub trait FileLoader {
    fn resolve_path(
        &self,
        path: AnchoredPath<'_>,
    ) -> Option<FileId>;
}

#[salsa::query_group(SourceDatabaseStorage)]
pub trait SourceDatabase: FileLoader {
    #[salsa::input]
    fn file_text(
        &self,
        file_id: FileId,
    ) -> Arc<String>;

    #[salsa::input]
    fn file_path(
        &self,
        file_id: FileId,
    ) -> VfsPath;

    #[salsa::input]
    fn file_id(
        &self,
        path: VfsPath,
    ) -> FileId;

    #[salsa::input]
    fn custom_imports(&self) -> Arc<FxHashMap<String, String>>;

    #[salsa::input]
    fn shader_defs(&self) -> Arc<FxHashSet<String>>;

    /// Path to a file, relative to the root of its source root.
    /// Source root of the file.
    #[salsa::input]
    fn file_source_root(
        &self,
        file_id: FileId,
    ) -> SourceRootId;
    /// Contents of the source root.
    #[salsa::input]
    fn source_root(
        &self,
        id: SourceRootId,
    ) -> Arc<SourceRoot>;

    #[salsa::invoke(parse_no_preprocessor_query)]
    fn parse_no_preprocessor(
        &self,
        key: FileId,
    ) -> syntax::Parse;

    #[salsa::invoke(parse_with_unconfigured_query)]
    fn parse_with_unconfigured(
        &self,
        key: FileId,
    ) -> (Parse, Arc<Vec<UnconfiguredCode>>);

    #[salsa::invoke(parse_query)]
    fn parse(
        &self,
        key: FileId,
    ) -> Parse;

    #[salsa::invoke(parse_import_no_preprocessor_query)]
    fn parse_import_no_preprocessor(
        &self,
        key: String,
    ) -> Result<syntax::Parse, ()>;

    #[salsa::invoke(parse_import_query)]
    fn parse_import(
        &self,
        key: String,
        parse_entrypoint: ParseEntryPoint,
    ) -> Result<Parse, ()>;

    fn line_index(
        &self,
        key: FileId,
    ) -> Arc<LineIndex>;
}

fn line_index(
    database: &dyn SourceDatabase,
    file_id: FileId,
) -> Arc<LineIndex> {
    let text = database.file_text(file_id);
    Arc::new(LineIndex::new(&text))
}

fn parse_no_preprocessor_query(
    database: &dyn SourceDatabase,
    file_id: FileId,
) -> syntax::Parse {
    let source = database.file_text(file_id);
    syntax::parse(&source)
}

#[expect(clippy::needless_pass_by_value, reason = "required by salsa")]
fn parse_import_no_preprocessor_query(
    database: &dyn SourceDatabase,
    key: String,
) -> Result<syntax::Parse, ()> {
    let imports = database.custom_imports();
    let source = imports.get(&key).ok_or(())?;
    Ok(syntax::parse(source))
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UnconfiguredCode {
    pub range: TextRange,
    pub definition: String,
}

fn parse_with_unconfigured_query(
    database: &dyn SourceDatabase,
    file_id: FileId,
) -> (Parse, Arc<Vec<UnconfiguredCode>>) {
    let shader_defs = database.shader_defs();
    let source = database.file_text(file_id);

    let mut unconfigured = Vec::new();

    let processed_source =
        shader_processor::get_shader_processor().process(&source, &shader_defs, |range, definition| {
            let range = TextRange::new(
                TextSize::from(u32::try_from(range.start).unwrap()),
                TextSize::from(u32::try_from(range.end).unwrap()),
            );
            unconfigured.push(UnconfiguredCode {
                range,
                definition: definition.to_owned(),
            });
        });
    let parse = syntax::parse(&processed_source);
    (parse, Arc::new(unconfigured))
}

fn parse_query(
    database: &dyn SourceDatabase,
    file_id: FileId,
) -> Parse {
    database.parse_with_unconfigured(file_id).0
}

#[expect(clippy::needless_pass_by_value, reason = "required by salsa")]
fn parse_import_query(
    database: &dyn SourceDatabase,
    key: String,
    parse_entrypoint: ParseEntryPoint,
) -> Result<Parse, ()> {
    let imports = database.custom_imports();
    let shader_defs = database.shader_defs();
    let source = imports.get(&key).ok_or(())?;

    let processed_source =
        shader_processor::get_shader_processor().process(source, &shader_defs, |_, _| {});
    Ok(syntax::parse_entrypoint(
        &processed_source,
        parse_entrypoint,
    ))
}

/// Silly workaround for cyclic deps between the traits
pub struct FileLoaderDelegate<T>(pub T);

impl<T: SourceDatabase> FileLoader for FileLoaderDelegate<&'_ T> {
    fn resolve_path(
        &self,
        path: AnchoredPath<'_>,
    ) -> Option<FileId> {
        // FIXME: this *somehow* should be platform agnostic...
        let source_root = self.0.file_source_root(path.anchor);
        let source_root = self.0.source_root(source_root);
        source_root.resolve_path(path)
    }
}
