version: 2

multi-ecosystem-groups:
  daily-dependencies:
    schedule:
      interval: daily
    commit-message:
      prefix: internal
    labels:
      - C-Dependencies
      - D-Trivial
      - S-Ready-to-Review
    cooldown:
      default-days: 7

updates:
  - package-ecosystem: cargo
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: daily-dependencies
    labels:
      - A-Language-Server
    cooldown: 
      default-days: 7
    groups:
      minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    patterns: ["*"]
    multi-ecosystem-group: daily-dependencies
    labels:
      - A-Build-System
    cooldown: 
      default-days: 7
    groups:
      codeql:
        patterns:
          - "github/codeql-action/*"
      minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /editors/code
    patterns: ["*"]
    multi-ecosystem-group: daily-dependencies
    labels:
      - A-Editor
    ignore:
      - dependency-name: "@types/vscode"
        update-types:
          - version-update:semver-minor
    cooldown: 
      default-days: 7
    groups:
      minor-patch:
        update-types:
          - minor
          - patch
        exclude-patterns:
          - "@types/vscode"

  - package-ecosystem: docker
    directory: /.github
    patterns: ["*"]
    multi-ecosystem-group: daily-dependencies
    labels:
      - A-Build-System
    cooldown: 
      default-days: 7
    groups:
      minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /editors/code
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    commit-message:
      prefix: internal
    labels:
      - A-Editor
      - C-Dependencies
      - D-Trivial
      - S-Ready-to-Review
    cooldown:
      default-days: 90
    allow:
      - dependency-name: "@types/vscode"
        update-types:
          - version-update:semver-minor
