version: 2

multi-ecosystem-groups:
  daily-dependencies:
    schedule:
      interval: daily
    commit-message:
      prefix: internal
    labels:
      - C-Dependencies
      - D-Trivial
      - S-Ready-to-Review
    cooldown:
      default-days: 7

updates:
  - package-ecosystem: cargo
    directory: /
    patterns: ["*"]
    update-types:
      - minor
      - patch
    multi-ecosystem-group: daily-dependencies
    labels:
      - A-Language-Server
    cooldown:
      default-days: 7

  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: internal
    labels:
      - A-Language-Server
      - C-Dependencies
      - S-Ready-to-Review
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"

  - package-ecosystem: github-actions
    directory: /
    patterns: ["*"]
    update-types:
      - minor
      - patch
    multi-ecosystem-group: daily-dependencies
    labels:
      - A-Build-System
    cooldown:
      default-days: 7
    groups:
      codeql:
        patterns:
          - "github/codeql-action/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: internal
    labels:
      - A-Build-System
      - C-Dependencies
      - S-Ready-to-Review
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"

  - package-ecosystem: npm
    directory: /editors/code
    patterns: ["*"]
    update-types:
      - minor
      - patch
    multi-ecosystem-group: daily-dependencies
    labels:
      - A-Editor
    ignore:
      - dependency-name: "@types/vscode"
        update-types:
          - "version-update:semver-minor"
    cooldown:
      default-days: 7

  - package-ecosystem: npm
    directory: /editors/code
    schedule:
      interval: daily
    commit-message:
      prefix: internal
    labels:
      - A-Editor
      - C-Dependencies
      - S-Ready-to-Review
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"

  - package-ecosystem: docker
    directory: /.github/actions/github-release
    patterns: ["*"]
    update-types:
      - minor
      - patch
    multi-ecosystem-group: daily-dependencies
    labels:
      - A-Build-System
    cooldown:
      default-days: 7

  - package-ecosystem: docker
    directory: /.github/actions/github-release
    schedule:
      interval: daily
    commit-message:
      prefix: internal
    labels:
      - A-Build-System
      - C-Dependencies
      - S-Ready-to-Review
    cooldown:
      default-days: 7
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"

  - package-ecosystem: npm
    directory: /editors/code
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    commit-message:
      prefix: internal
    labels:
      - A-Editor
      - C-Dependencies
      - D-Trivial
      - S-Ready-to-Review
    cooldown:
      default-days: 90
    allow:
      - dependency-name: "@types/vscode"
        update-types:
          - version-update:semver-minor
