version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    commit-message:
      prefix: internal
    labels:
      - A-Language-Server
      - C-Dependencies
      - D-Trivial
      - S-Ready-to-Review
    cooldown:
      default-days: 7
    groups:
      minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    commit-message:
      prefix: internal
    labels:
      - A-Build-System
      - C-Dependencies
      - D-Trivial
      - S-Ready-to-Review
    cooldown:
      default-days: 7
    groups:
      codeql:
        patterns:
          - "github/codeql-action/*"
      minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /editors/code
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    commit-message:
      prefix: internal
    labels:
      - A-Editor
      - C-Dependencies
      - D-Trivial
      - S-Ready-to-Review
    cooldown:
      default-days: 7
    groups:
      minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: /.github
    schedule:
      interval: daily
    open-pull-requests-limit: 20
    commit-message:
      prefix: internal
    labels:
      - A-Build-System
      - C-Dependencies
      - D-Trivial
      - S-Ready-to-Review
    cooldown:
      default-days: 7
    groups:
      minor-patch:
        update-types:
          - minor
          - patch
