[graph]
all-features = true

[advisories]
version = 2
ignore = [
  # TODO: #157 - Delete this once salsa has been bumped.
  "RUSTSEC-2024-0384",
]

# Ignore warnings about unused license exceptions
[licenses]
version = 2
allow = [
  "0BSD",
  "Apache-2.0 WITH LLVM-exception",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BSL-1.0",
  "CC0-1.0",
  "ISC",
  "MIT-0",
  "MIT",
  "MPL-2.0",
  "Unicode-3.0",
  "Unlicense",
  "Zlib",
]

exceptions = [{ name = "unicode-ident", allow = ["Unicode-DFS-2016"] }]

[bans]
multiple-versions = "warn"
wildcards = "deny"
# Certain crates that we do not want multiple versions of in the dependency tree
deny = []

[sources]
unknown-registry = "warn"
unknown-git = "warn"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
