[package]
name = "simple-cargo"
version = "0.0.0"
edition = "2024"
description = "testing that a WESL project can be loaded from Cargo metadata with dependencies"

[package.metadata.wgsl-analyzer]
edition = "2026_pre"
root = "."

[package.metadata.wgsl-analyzer.dependencies]
simple_wesl = { path = "../simple_wesl" }
nested = { path = "./nested" }

[workspace]
