[package]
name = "bevy_gizmos_render"
version = "0.20.0-dev"
edition = "2024"
description = "Provides gizmos rendering for Bevy Engine"
homepage = "https://bevy.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]

[features]
webgl = []
webgpu = []

[dependencies]
# Bevy
bevy_pbr = { path = "../bevy_pbr", version = "0.20.0-dev", optional = true }
bevy_sprite_render = { path = "../bevy_sprite_render", version = "0.20.0-dev", optional = true }
bevy_render = { path = "../bevy_render", version = "0.20.0-dev" }
bevy_core_pipeline = { path = "../bevy_core_pipeline", version = "0.20.0-dev" }

# other
bytemuck = "1.0"
tracing = { version = "0.1", default-features = false, features = ["std"] }

[package.metadata.docs.rs]
rustdoc-args = [
  "-Zunstable-options",
  "--generate-link-to-definition",
  "--generate-macro-expansion",
]
all-features = true

[package.metadata.wgsl-analyzer]
edition = "2026_pre"
root = "src"

[package.metadata.wgsl-analyzer.dependencies]
bevy_render = { path = "../bevy_render" }
