name: GitHub release
description: Create a GitHub release
inputs:
  token:
    description: PAT for GitHub with release permission
    required: true
  name:
    description: Name/title of the release
    required: true
  files:
    description: Files to publish in the release
    required: true
runs:
  using: docker
  image: Dockerfile
