[package]
name = "bevy"
version = "0.20.0-dev"

[workspace]
resolver = "3"
members = [
  "crates/*",
]

[dependencies]
tracing = { version = "0.1", default-features = false, optional = true }

[package.metadata.wgsl-analyzer]
edition = "2026_pre"
root = "assets/shaders"

[package.metadata.wgsl-analyzer.dependencies]
bevy_render = { path = "crates/bevy_render" }
bevy_pbr = { path = "crates/bevy_pbr" }
bevy_core_pipeline = { path = "crates/bevy_core_pipeline" }
bevy_sprite_render = { path = "crates/bevy_sprite_render" }
bevy_ui_render = { path = "crates/bevy_ui_render" }
