[package]
name = "errors"
edition.workspace = true
description = "Documentation and tests for error codes"
publish = false
readme = "README.md"
keywords = ["wgsl"]
repository.workspace = true
license.workspace = true

[dependencies]

[lints]
workspace = true
