[package]
name = "bevy_render"
version = "0.20.0-dev"
edition = "2024"
description = "Provides rendering functionality for Bevy Engine"
homepage = "https://bevy.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]

[dependencies]
# bevy

# rendering
image = { version = "0.25.2", default-features = false }

# misc
# `fragile-send-sync-non-atomic-wasm` feature means we can't use Wasm threads for rendering
# It is enabled for now to avoid having to do a significant overhaul of the renderer just for wasm.
# When the 'atomics' feature is enabled `fragile-send-sync-non-atomic` does nothing
# and Bevy instead wraps `wgpu` types to verify they are not used off their origin thread.
wgpu = { version = "30", default-features = false, features = [
  "wgsl",
  "dx12",
  "metal",
  "vulkan",
  "fragile-send-sync-non-atomic-wasm",
] }
wgpu-types = { version = "30", default-features = false }
bytemuck = { version = "1.5", features = ["derive", "must_cast"] }
downcast-rs = { version = "2", default-features = false, features = ["std"] }
thiserror = { version = "2", default-features = false }
derive_more = { version = "2", default-features = false, features = ["from"] }
encase = "0.12"
glam = { version = "0.33.2", default-features = false, features = [
  "std",
  "encase",
] }
# For wgpu profiling using tracing. Use `RUST_LOG=info` to also capture the wgpu spans.
profiling = { version = "1", features = [
  "profile-with-tracing",
], optional = true }
async-channel = "2.3.0"
nonmax = "0.5"
smallvec = { version = "1", default-features = false, features = ["const_new"] }
offset-allocator = "0.2"
variadics_please = "2.0"
tracy-client = { version = "0.18.3", optional = true }
indexmap = { version = "2" }
bitflags = "2"
itertools = "0.15"
weak-table = "0.4"
tracing = "0.1"
static_assertions = "1"

[dev-dependencies]
proptest = "1"
proptest-derive = "0.8"
# noop backend used for tests via test_utils.rs
wgpu = { version = "30", default-features = false, features = ["noop"] }

[target.'cfg(all(target_arch = "wasm32", target_feature = "atomics"))'.dependencies]
send_wrapper = { version = "0.6.0" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
js-sys = "0.3.83"
web-sys = { version = "0.3.67", features = [
  'Blob',
  'Document',
  'Element',
  'HtmlElement',
  'Node',
  'Url',
  'Window',
] }
wasm-bindgen = "0.2"

[package.metadata.docs.rs]
rustdoc-args = [
  "-Zunstable-options",
  "--generate-link-to-definition",
  "--generate-macro-expansion",
]
all-features = true

[package.metadata.wgsl-analyzer]
edition = "2026_pre"
root = "src"

[package.metadata.wgsl-analyzer.dependencies]
bevy_core_pipeline = { path = "../bevy_core_pipeline" }
