name: Weekly beta CI test

on:
  schedule:
    - cron: '0 12 * * 1'
  workflow_dispatch:

permissions: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Rust beta toolchain
        uses: dtolnay/rust-toolchain@beta

      - name: Install Linux dependencies
        run: cargo test --workspace --lib --bins --tests --benches
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: '-C debuginfo=0 -D warnings'

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install Rust beta toolchain
        uses: dtolnay/rust-toolchain@beta
        with:
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

  check-compiles:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: test
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-check-doc-${{ hashFiles('**/Cargo.toml') }}

      - name: Install Rust beta toolchain
        uses: dtolnay/rust-toolchain@beta

      - name: Check Compile
        run: |
          cargo test --target-dir ../../../target
          # cargo check --benches --target-dir ../target --manifest-path ./benches/Cargo.toml
          cargo check --workspace --examples
          cargo check --workspace
          cargo check --workspace --tests

  rustdoc:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-check-doc-${{ hashFiles('**/Cargo.toml') }}

      - name: Install Rust beta toolchain
        uses: dtolnay/rust-toolchain@beta

      - name: Build documentation
        run: cargo doc --workspace --all-features --no-deps --document-private-items --keep-going
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: -C debuginfo=0

      - name: Check doc
        run: cargo test --workspace --doc
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: -C debuginfo=0 --cfg

      - name: Installs cargo-deadlinks
        run: cargo install --force cargo-deadlinks

      - name: Checks dead links
        run: cargo deadlinks --dir target/doc
        continue-on-error: true

  open-issue:
    name: Warn that weekly CI fails
    runs-on: ubuntu-latest
    needs: [test, lint, check-compiles, rustdoc]
    permissions:
      issues: write
    # Use always() so the job does not get canceled if any other jobs fail
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - name: Create issue
        run: |
          previous_issue_number=$(gh issue list \
            --search "$TITLE in:title" \
            --json number \
            --jq '.[0].number')
          if [[ -n $previous_issue_number ]]; then
            gh issue comment $previous_issue_number \
              --body "Weekly pipeline still fails: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          else
            gh issue create \
              --title "$TITLE" \
              --label "$LABELS" \
              --body "$BODY"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          TITLE: Main branch fails to pass CI on Rust beta.
          LABELS: C-Bug,S-Needs-Triage
          BODY: |
            ## Weekly CI run has failed.
            [The offending run.](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
