[package]
name = "bevy_ui_render"
version = "0.20.0-dev"
edition = "2024"
description = "Provides rendering functionality for Bevy UI"
homepage = "https://bevyengine.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]

[dependencies]
# bevy
bevy_core_pipeline = { path = "../bevy_core_pipeline", version = "0.20.0-dev" }
bevy_render = { path = "../bevy_render", version = "0.20.0-dev" }
bevy_sprite_render = { path = "../bevy_sprite_render", version = "0.20.0-dev", features = [
] }

# other
bytemuck = { version = "1.5", features = ["derive"] }
derive_more = { version = "2", default-features = false, features = ["from"] }
tracing = { version = "0.1", default-features = false, features = ["std"] }
indexmap = { version = "2" }
smallvec = { version = "1", default-features = false }

[package.metadata.docs.rs]
rustdoc-args = [
  "-Zunstable-options",
  "--generate-link-to-definition",
  "--generate-macro-expansion",
]
all-features = true

[package.metadata.wgsl-analyzer]
edition = "2026_pre"
root = "src"

[package.metadata.wgsl-analyzer.dependencies]
bevy_render = { path = "../bevy_render" }
constants = { path = "../../constants" }
